name: Run Python
on:
    push:
    schedule:
      - cron: 0 0 * * * # run at every end of a day
jobs:
    build:
        name: set and run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: step1
              run: |
                python3 main.p
